[CoreRedirects]
# Pre v1.0 Redirects
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryWidgetInterface",NewName="/Script/UICS.ViewWidgetInterface")
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryCommonButtonBase",NewName="/Script/UICS.ViewCommonButtonBase")
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryUserWidget",NewName="/Script/UICS.ViewUserWidget")
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryCommonUserWidget",NewName="/Script/UICS.ViewCommonUserWidget")
+ClassRedirects=(OldName="/Script/UIPowerTools.DataScreenContentProvider",NewName="/Script/UICS.UIDataProvider")
+ClassRedirects=(OldName="/Script/UIPowerTools.Screen",NewName="/Script/UICS.UICSScreen")
+PropertyRedirects=(OldName="/Script/UIPowerTools.ViewScreenComponent.EntryWidgetPrototype", NewName="/Script/UICS.ViewScreenComponent.ViewWidgetPrototype")
+PropertyRedirects=(OldName="/Script/UIPowerTools.ViewScreenComponent.OnAction",NewName="/Script/UICS.ViewScreenComponent.OnInputAction")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UICSAccessor.GetScreenComponent_BP",NewName="/Script/UICS.UIPTStatics.GetScreenComponent_BP")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UICSAccessor.GetScreenComponent_BP",NewName="/Script/UICS.UIPTStatics.GetScreenComponent_BP")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UIDataProvider.BP_Setup",NewName="/Script/UICS.BP_BeginRetrieveEntries")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UIDataProvider.BP_Teardown",NewName="/Script/UICS.BP_EndRetrieveEntries")
+FunctionRedirects=(OldName="/Script/UIPowerTools.ActionScreenComponentProvider.CanExecuteActionInternal",NewName="/Script/UICS.ActionScreenComponentProvider.BP_CanExecuteAction")
+FunctionRedirects=(OldName="/Script/UIPowerTools.ActionScreenComponentProvider.ExecuteActionInternal",NewName="/Script/UICS.ActionScreenComponentProvider.BP_ExecuteAction")
+PackageRedirects=(OldName="/Script/UIPowerTools",NewName="/Script/UICS")
+PackageRedirects=(OldName="/Script/UIPowerTools",Removed=true)
 