[CoreRedirects]
# Redirects put in when project was called UI Power Tools
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryWidgetInterface",NewName="/Script/UICS.ViewWidgetInterface")
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryCommonButtonBase",NewName="/Script/UICS.ViewCommonButtonBase")
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryUserWidget",NewName="/Script/UICS.ViewUserWidget")
+ClassRedirects=(OldName="/Script/UIPowerTools.EntryCommonUserWidget",NewName="/Script/UICS.ViewCommonUserWidget")
+ClassRedirects=(OldName="/Script/UIPowerTools.DataScreenContentProvider",NewName="/Script/UICS.UIDataProvider")
+ClassRedirects=(OldName="/Script/UIPowerTools.Screen",NewName="/Script/UICS.UICSScreen")
+PropertyRedirects=(OldName="/Script/UIPowerTools.ViewScreenComponent.EntryWidgetPrototype", NewName="/Script/UICS.ViewScreenComponent.ViewWidgetPrototype")
+PropertyRedirects=(OldName="/Script/UIPowerTools.ViewScreenComponent.OnAction",NewName="/Script/UICS.ViewScreenComponent.OnInputAction")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UICSAccessor.GetScreenComponent_BP",NewName="/Script/UICS.UIPTStatics.GetScreenComponent_BP")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UICSAccessor.GetScreenComponent_BP",NewName="/Script/UICS.UIPTStatics.GetScreenComponent_BP")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UIDataProvider.BP_Setup",NewName="/Script/UICS.BP_BeginRetrieveEntries")
+FunctionRedirects=(OldName="/Script/UIPowerTools.UIDataProvider.BP_Teardown",NewName="/Script/UICS.BP_EndRetrieveEntries")
+FunctionRedirects=(OldName="/Script/UIPowerTools.ActionScreenComponentProvider.CanExecuteActionInternal",NewName="/Script/UICS.ActionScreenComponentProvider.BP_CanExecuteAction")
+FunctionRedirects=(OldName="/Script/UIPowerTools.ActionScreenComponentProvider.ExecuteActionInternal",NewName="/Script/UICS.ActionScreenComponentProvider.BP_ExecuteAction")
+PackageRedirects=(OldName="/Script/UIPowerTools",NewName="/Script/UICS")
+PackageRedirects=(OldName="/Script/UIPowerTools",Removed=true)

# Pre v1.0 Redirects
+FunctionRedirects=(OldName="/Script/UICS.DataScreenComponent.SetDataRetriever",NewName="/Script/UICS.DataScreenComponent.SetDataProvider")
+FunctionRedirects=(OldName="/Script/UICS.DataScreenComponent.SetDataRetrieverFromClass",NewName="/Script/UICS.DataScreenComponent.SetDataProviderFromClass")
+FunctionRedirects=(OldName="/Script/UICS.DataScreenComponent.GetDataRetriever",NewName="/Script/UICS.DataScreenComponent.SetDataProvider")
+FunctionRedirects=(OldName="/Script/UICS.DataScreenComponent.HasDataRetriever",NewName="/Script/UICS.DataScreenComponent.HasDataProvider")
+ClassRedirects=(OldName="/Script/UICS.ViewUserWidget",NewName="/Script/UICS.DisplayUserWidget")
+ClassRedirects=(OldName="/Script/UICS.ViewCommonButtonBase",NewName="/Script/UICS.DisplayCommonButtonBase")
+ClassRedirects=(OldName="/Script/UICS.ViewCommonActivatableWidget",NewName="/Script/UICS.DisplayCommonActivatableWidget")
+ClassRedirects=(OldName="/Script/UICS.ViewCommonUserWidget",NewName="/Script/UICS.DisplayCommonUserWidget")
+ClassRedirects=(OldName="/Script/UICS.ViewScreenComponent",NewName="/Script/UICS.DisplayScreenComponent")
+ClassRedirects=(OldName="/Script/UICS.Tooltip",NewName="/Script/UICS.UICSTooltip")
+PropertyRedirects=(OldName="/Script/UICS.DisplayScreenComponent.ActiveViewWidgets",NewName="/Script/UICS.DisplayScreenComponent.ActiveDisplayWidgets")
+PropertyRedirects=(OldName="/Script/UICS.DisplayScreenComponent.ViewWidgetPrototype",NewName="/Script/UICS.DisplayScreenComponent.DisplayWidgetPrototype")
+FunctionRedirects=(OldName="/Script/UICS.DisplayScreenComponent.GetAllViewWidgets",NewName="/Script/UICS.DisplayScreenComponent.GetAllDisplayWidgets")
+FunctionRedirects=(OldName="/Script/UICS.DisplayScreenComponent.GetAllWidgets",NewName="/Script/UICS.DisplayScreenComponent.GetAllDisplayWidgetsAsUserWidgets")
 